apps/accounts/urls.py
from django.urls import path
from .views import *

app_name="accounts"
urlpatterns = [
    path("register/",RegisterUserView.as_view(),name="register"),
    path("verify/",VerifyRegisterCodeView.as_view(),name="Verify"),
    path('login/',LoginUserView.as_view(),name="Login"),
    path('logout/',LogoutUserView.as_view(),name="Logout"),
    path('userpanel/',UserPanelView.as_view(),name="userpanel"),
    path('change_password/',ChangePasswordView.as_view(),name="change_password"),
    path('remember_password/',RemeberPasswordView.as_view(),name="remember_password"),
     path("show_last_orders/",show_last_orders,name="show_last_orders"),
    path("update_profile/",UpdateProfileView.as_view(),name="update_profile"),
    path("show_user_payments/",show_user_payments,name="show_user_payments"),
    path("return_to_shop_cart/<uuid:order_code>/",return_to_shop_cart,name="return_to_shop_cart"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("orders/",include("apps.orders.urls",namespace="orders")),
    path("discounts/",include("apps.discounts.urls",namespace="discounts")),
    path("payments/",include("apps.payments.urls",namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls",namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace="csf")),
    path("search/",include("apps.search.urls",namespace="search")),
    path("test_api/",include("apps.test_api.urls",namespace="test_api")),
    
    
    path("ckeditor",include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = "apps.main.views.handler404"

templates/accounts_app/Change_Password.html
{% extends "main_template.html" %}

{% block title %}
فروشگاه درسمن
{% endblock title %}
{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
								<li class="breadcrumb-item"><a href="index.html">خانه</a>
									/
								</li>
								<li class="breadcrumb-item">
									<a href=""> تغییر رمز حساب کاربری </a>
									/
								</li>
								<li class="active" aria-current="page"> تغییر رمز حساب کاربری</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
						<h1>ایجاد حساب کاربری جدید</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6 d-flex mt-4 mt-md-0">
							<div class="card flex-grow-1 mb-0">
								<div class="card-body">
									<h3 class="card-title">تغییر رمز عبور</h3>
									
                                    <form action="" method="post">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                            <button type="submit" class="btn btn-primary mt-4">ثبت تغییرات</button>
                                        </form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->


{% endblock content %}

templates/accounts_app/Login.html
{% extends "main_template.html" %}

{% block title %}
Darsman Shop
{% endblock title %}


{% block content %}
<!-- site__body -->
<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">Home</a>
                            /
                        </li>
                        <li class="breadcrumb-item">
                            <a href="#">User Account</a>
                            /
                        </li>
                        <li class="active" aria-current="page">Login to User Account</li>
                    </ol>
                </nav>
            </div>
            <div class="page-header__title d-flex justify-content-center">
                <h1>Login to User Account</h1>
            </div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">
                    <div class="card flex-grow-1 mb-md-0">
                        <div class="card-body">
                            <h3 class="card-title">Login</h3>
                            <form action="" method="post">
                                {% csrf_token %}
                                {{form.as_p}}
                                <div>
                                    <a href="{% url "accounts:remember_password" %}">
                                        Forgot Password
                                    </a>
                                </div>
                                <button type="submit" class="btn btn-primary mt-4">Login</button>
                                {% comment %} <div class="form-group">
                                    <label>آدرس ایمیل</label>
                                    <input type="email" class="form-control" placeholder="ایمیل را وارد کنید">
                                </div>
                                <div class="form-group">
                                    <label>رمز عبور</label>
                                    <input type="password" class="form-control" placeholder="رمز عبور را وارد کنید"> <small class="form-text text-muted"><a href="">فراموشی رمز عبور</a></small></div>
                                <div class="form-group">
                                    <div class="form-check"><span class="form-check-input input-check"><span class="input-check__body"><input class="input-check__input" type="checkbox" id="login-remember"> <span class="input-check__box"></span>
                                        <svg class="input-check__icon" width="9px" height="7px">
                                            <use xlink:href="images/sprite.svg#check-9x7"></use>
                                        </svg>
                                        </span>
                                        </span>
                                        <label class="form-check-label" for="login-remember">به خاطر سپاری</label>
                                    </div>
                                </div> {% endcomment %}
                                
                            </form>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- site__body / end -->
{% endblock content %}

templates/accounts_app/Verify_Register_Code.html
{% extends "main_template.html" %}

{% block title %}
فروشگاه درسمن
{% endblock title %}


{% block content %}
<!-- site__body -->
<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">خانه</a>
                            /
                        </li>
                        <li class="breadcrumb-item">
                            <a href="#">حساب کاربری</a>
                            /
                        </li>
                        <li class="active" aria-current="page">احراز هویت</li>
                    </ol>
                </nav>
            </div>
            <div class="page-header__title d-flex justify-content-center">
                <h1>تایید شماره موبایل</h1>
            </div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">
                    <div class="card flex-grow-1 mb-md-0">
                        <div class="card-body">
                            
                            <form action="" method="post">
                                    {% csrf_token %}
                                    <label>کد دریافتی</label>
                                    {{form.as_p}}
                                    
                                    <button type="submit" class="btn btn-primary mt-4">ارسال کد</button>
                            </form>
                                
                                    
                                    
                                

                                
                            
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- site__body / end -->

{% endblock content %}

templates/accounts_app/register.html
{% extends "main_template.html" %}

{% block title %}
Darsman Shop
{% endblock title %}
{% block content %}
		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
									<li class="breadcrumb-item"><a href="index.html">Home</a>
									/
								</li>
								<li class="breadcrumb-item">
										<a href="">User Account</a>
									/
								</li>
									<li class="active" aria-current="page"> Create User Account</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title d-flex justify-content-center">
								<h1>Create New User Account</h1></div>
				</div>
			</div>
			<div class="block">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="col-md-6 d-flex mt-4 mt-md-0">
							<div class="card flex-grow-1 mb-0">
								<div class="card-body">
									<h3 class="card-title">Register</h3>
									
                                    <form action="" method="post">
                                            {% csrf_token %}
                                            {{ form.as_p }}
                                            <button type="submit" class="btn btn-primary mt-4">Register</button>
                                        </form>                                         
										{% comment %} <div class="form-group">
											<label>موبایل</label>
											<input type="text" class="form-control" placeholder="موبایل را وارد کنید">
										</div>
										<div class="form-group">
											<label>رمز عبور</label>
											<input type="password" class="form-control" placeholder="رمز عبور را وارد کنید">
										</div>
										<div class="form-group">
											<label>تکرار رمز عبور</label>
											<input type="password" class="form-control" placeholder="رمز عبور را وارد کنید">
										</div>
										<button type="submit" class="btn btn-primary mt-4">Register</button>
									 {% endcomment %}
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
		<!-- site__body / end -->


{% endblock content %}

templates/accounts_app/remeber_password.html
{% extends "main_template.html" %}

{% block title %}
فروشگاه درسمن
{% endblock title %}


{% block content %}
<!-- site__body -->
<div class="site__body">
    <div class="page-header">
        <div class="page-header__container container">
            <div class="page-header__breadcrumb">
                <nav aria-label="breadcrumb">
                    <ol class="breadcrumb">
                        <li class="breadcrumb-item"><a href="index.html">خانه</a>
                            /
                        </li>
                        <li class="breadcrumb-item">
                            <a href="#">حساب کاربری</a>
                            /
                        </li>
                        <li class="active" aria-current="page">احراز هویت</li>
                    </ol>
                </nav>
            </div>
            <div class="page-header__title d-flex justify-content-center">
                <h1>ارسال شماره موبایل جهت تغییر رمز عبور</h1>
            </div>
        </div>
    </div>
    <div class="block">
        <div class="container">
            <div class="row d-flex justify-content-center">
                <div class="col-md-6">
                    <div class="card flex-grow-1 mb-md-0">
                        <div class="card-body">
                            
                            <form action="" method="post">
                                    {% csrf_token %}
                                    <label>شماره موبایل</label>
                                    {{form.as_p}}
                                    
                                    <button type="submit" class="btn btn-primary mt-4">ارسال </button>
                            </form>
                                
                                    
                                    
                                

                                
                            
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
</div>
<!-- site__body / end -->

{% endblock content %}

templates/accounts_app/show_user_payments.html
{% extends "userpanel_template.html" %}
{% load humanize %}
{% load render_partial %}

{% block title %}سابقه ی پرداخت{% endblock title %}

{% block content %}
<div class="dashboard__orders card">
    <div class="card-header">
        <h5>لیست پرداخت های شما</h5>
    </div>
    <div class="card-divider"></div>
    <div class="card-table">
        <div class="table-responsive-sm">
            <table>
                <thead>
                    <tr>
                        <th>شماره پرداخت</th>
                        <th>تاریخ</th>
                        <th>وضعیت</th>
                        <th>مبلغ پرداختی</th>
                        <th>تکمیل خرید</th>
                    </tr>
                </thead>
                <tbody>
                    {% for payment in payments %}
                        <tr>
                            <td><a href="">{{payment.id}}</a></td>
                            <td>{{payment.register_date}}</td>
                            <td>
                                {% if payment.is_finally %}
                                <span class="text-success">پرداخت شده</span>
                                {% else %}
                                <span class="text-danger">پرداخت نشده</span>
                                {% endif %}
                            </td>
                            <td>{{payment.amount|intcomma}} تومان</td>
                            
                            <td>
                                {% if payment.is_finally %}
                                <span class="text-success"><h4>موفقیت آمیز</h4></span>
                                {% else %}
                                <div class="form-group">
                                    <a href="{% url "account:return_to_shop_cart" payment.order.order_code %}" class="btn btn-danger mt-4">تکمیل خرید</a>
                                </div>
                                {% endif %}
                            </td>
                        </tr>
                    {% endfor %}

                </tbody>
            </table>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts_app/update_profile.html
{% extends "userpanel_template.html" %}
{% block title %}ویرایش اطلاعات{% endblock title %}

{% block content %}
<div class="block">
    <div class="container">
        <div class="row d-flex justify-content-center">
            <div class="col-md-9">
                <div class="card flex-grow-1 mb-md-0">
                    <div class="card-body">
                        <h3 class="card-title">ویرایش پروفایل</h3>

                        {% comment %} اگه به اکشن ادرس ندی به پشت خودش برمیگرده {% endcomment %}
                        <form action="" method="post" enctype="multipart/form-data">
                            {% csrf_token %}
                            {{form.as_p}}
                            {% if image_url %}
                            <img src="{{media_url}}{{image_url}}" style="width: 100px; height: 100px;" alt="">
                            {% else %}
                            <img src="{{media_url}}images/customer/nophotom.png" style="width: 100px; height: 100px;" alt="">
                            {% endif %}
                            <div class="form-group">
                                <button type="submit" class="btn btn-primary mt-4">ویرایش</button>
                                <a href="{% url "accounts:userpanel" %}" class="btn btn-info mt-4">انصراف</a>
                            </div>

                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/accounts_app/userpanel.html
{% extends "userpanel_template.html" %}
{% load render_partial %}

{% block title %}User Panel{% endblock title %}

{% block content %}
    <div class="dashboard">
        {% include "accounts_app/partials/user_info.html" %}
        {% render_partial "accounts:show_last_orders" %}
    </div>
{% endblock content %}