apps/accounts/urls.py
from django.urls import path
from .views import *

app_name="accounts"
urlpatterns = [
    path("register/",RegisterUserView.as_view(),name="register"),
    path("verify/",VerifyRegisterCodeView.as_view(),name="Verify"),
    path('login/',LoginUserView.as_view(),name="Login"),
    path('logout/',LogoutUserView.as_view(),name="Logout"),
    path('userpanel/',UserPanelView.as_view(),name="userpanel"),
    path('change_password/',ChangePasswordView.as_view(),name="change_password"),
    path('remember_password/',RemeberPasswordView.as_view(),name="remember_password"),
     path("show_last_orders/",show_last_orders,name="show_last_orders"),
    path("update_profile/",UpdateProfileView.as_view(),name="update_profile"),
    path("show_user_payments/",show_user_payments,name="show_user_payments"),
    path("return_to_shop_cart/<uuid:order_code>/",return_to_shop_cart,name="return_to_shop_cart"),
]

apps/comment_scoring_favorites/urls.py
from django.urls import path
from . import views

app_name = 'csf'

urlpatterns = [
    path("create_comment/<slug:slug>/",views.CommentView.as_view(),name="create_comment"),
    path("add_score/",views.add_score,name="add_score"),
    path("add_to_favorites/",views.add_to_favorites,name="add_to_favorites"),
    path("user_favorites/",views.UserFavoriteView.as_view(),name="user_favorites"),
    path("status_of_favorite/",views.status_of_favorite,name="status_of_favorite"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("orders/",include("apps.orders.urls",namespace="orders")),
    path("discounts/",include("apps.discounts.urls",namespace="discounts")),
    path("payments/",include("apps.payments.urls",namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls",namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace="csf")),
    path("search/",include("apps.search.urls",namespace="search")),
    path("test_api/",include("apps.test_api.urls",namespace="test_api")),
    
    
    path("ckeditor",include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = "apps.main.views.handler404"

templates/main_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>SamShop|{% block title %}{% endblock title %}</title>
    <link rel="icon" type="image/png" href="images/favicon.png">

    
	<!-- css since all these are in the static folder we add static before them -->
	<link rel="stylesheet" href="{% static "vendor/bootstrap-4.5.3/css/bootstrap.min.css" %}">
	<link rel="stylesheet" href="{% static "vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css" %}">
	<link rel="stylesheet" href="{% static "css/style.css" %}">
	<link rel="stylesheet" href="{% static "css/custom.css" %} ">
	<!-- js -->
	<script src="{% static "vendor/jquery-3.3.1/jquery.min.js" %} "></script>
	<script src="{% static "vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js" %} "></script>
	<script src="{% static "vendor/owl-carousel-2.3.4/owl.carousel.min.js" %} "></script>
	<script src="{% static "js/main.js" %} "></script>
	<!-- font - fontawesome -->
	<link rel="stylesheet" href="{% static "vendor/fontawesome-5.6.3/css/all.min.css" %} ">
	<script src="/static/js/myscript.js"></script>

</head>
<body>
    {% include "partials/header.html" %}
	{% include "partials/messages.html" %}
    {% block content %}
    
    {% endblock content %}
    {% include "partials/footer.html" %}
</body>
</html>

templates/userpanel_template.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}{% endblock title %}</title>
    
    <link rel="icon" type="image/png" href="{{media_url}}images/favicon2.png">

    <link rel="stylesheet" href="{% static 'vendor/bootstrap-4.5.3/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/owl-carousel-2.3.4/assets/owl.carousel.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">

    <script src="{% static 'vendor/jquery-3.3.1/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/bootstrap-4.5.3/js/bootstrap.bundle.min.js' %}"></script>
    <script src="{% static 'vendor/owl-carousel-2.3.4/owl.carousel.min.js' %}"></script>
    <script src="{% static 'js/main.js' %}"></script>
    <script src="{% static 'js/test.js' %}"></script>

    <link rel="stylesheet" href="{% static 'vendor/fontawesome-5.6.3/css/all.min.css' %}">
    

</head>
<body>

    {% include "partials/accounts/user_panel_header.html" %}
    {% include "partials/messages.html" %}

    <div class="site__body">
        <div class="page-header">
            <div class="page-header__container container">
                <div class="page-header__title">
                    <h1>حساب کاربری</h1>
                </div>
            </div>
            <div class="block">
                <div class="container">
                    <div class="row">
                        <div class="col-12 col-lg-3 d-flex">
                            <div class="account-nav flex-grow-1">
                                <h4 class="account-nav__title">منوی اصلی</h4>

                                <ul>
                                    <li class="account-nav__item account-nav__item--active">
                                        <a href="{% url 'accounts:userpanel' %}">داشبورد</a>
                                      </li>
                                      
                                    <li class="account-nav__item"><a href="{% url "accounts:update_profile" %}">ویرایش پروفایل</a></li>
                                    <li class="account-nav__item"><a href="{% url "accounts:show_user_payments" %}">سابقه ی پرداخت</a></li> 
                                    <li class="account-nav__item"><a href="{% url "accounts:change_password" %}">تغییر رمز عبور</a></li>
                                    <li class="account-nav__item account-nav__item--active"><a href="{% url "csf:user_favorites" %}">محصولات مورد علاقه</a></li>
                                    <li class="account-nav__item"><a href="{% url "accounts:Logout" %}">خروج</a></li>
                                </ul>
                            </div>
                        </div>
                        <div class="col-12 col-lg-9 mt-4 mt-lg-0">
                    
                                {% block content %}
                                {% endblock content %}
                            
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    {% include "partials/footer.html" %}
    {% comment %} {% include "partials/script.html" %} {% endcomment %}
    
</body>
</html>