apps/accounts/urls.py
from django.urls import path
from .views import *

app_name="accounts"
urlpatterns = [
    path("register/",RegisterUserView.as_view(),name="register"),
    path("verify/",VerifyRegisterCodeView.as_view(),name="Verify"),
    path('login/',LoginUserView.as_view(),name="Login"),
    path('logout/',LogoutUserView.as_view(),name="Logout"),
    path('userpanel/',UserPanelView.as_view(),name="userpanel"),
    path('change_password/',ChangePasswordView.as_view(),name="change_password"),
    path('remember_password/',RemeberPasswordView.as_view(),name="remember_password"),
     path("show_last_orders/",show_last_orders,name="show_last_orders"),
    path("update_profile/",UpdateProfileView.as_view(),name="update_profile"),
    path("show_user_payments/",show_user_payments,name="show_user_payments"),
    path("return_to_shop_cart/<uuid:order_code>/",return_to_shop_cart,name="return_to_shop_cart"),
]

apps/products/urls.py
from django.urls import path
from .views import *

app_name="products"
urlpatterns = [
    path("cheapest_products/",get_cheapest_products,name="cheapest_products"),
    path("last_products/",get_last_products,name="last_products"),
    path('popular_products_group/',get_popular_product_groups,name="popular_products_group"),
    path("product_details/<slug:slug>/",ProductDetailView.as_view(),name="product_details"),
    path("related_product/<slug:slug>/",get_related_products,name="related_product"),
    path("product_groups/",ProductGroupsView.as_view(),name="product_groups"),
    path("product_of_group/<slug:slug>/",ProductsByGroupView.as_view(),name="product_of_group"),
    path("ajax_admin/",filter_value_for_feature,name='filter_value_for_feature'),
    path("product_groups_partial/",get_product_groups,name="product_groups_partial"),
    path('filtering_product_brands_partial/<slug:slug>',get_brands,name="filtering_product_brands_partial"),
    path('filtering_features_partial/<slug:slug>',get_features_for_filtre,name="filtering_features_partial"),
    path('compare_list/',ShowCompareListView.as_view(),name='compare_list'),
    path('compare_table/',compare_table,name='compare_table'),
    path('add_to_compare_list/',add_to_compare_list,name='add_to_compare_list'),
    path('delete_from_compare_list/',delete_from_compare_list,name='delete_from_compare_list'),
    path('status_of_compare_list/',status_of_compare_list,name='status_of_compare_list'),

]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("orders/",include("apps.orders.urls",namespace="orders")),
    path("discounts/",include("apps.discounts.urls",namespace="discounts")),
    path("payments/",include("apps.payments.urls",namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls",namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace="csf")),
    path("search/",include("apps.search.urls",namespace="search")),
    path("test_api/",include("apps.test_api.urls",namespace="test_api")),
    
    
    path("ckeditor",include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = "apps.main.views.handler404"

apps/products/views.py
from django.shortcuts import render,redirect
from .models import Product,PoductGroup,FeatureValue,Brand
from django.db.models import Q,Count,Min,Max
from django.views import View
from django.shortcuts import get_object_or_404
from django.http  import JsonResponse
from django.core.paginator import Paginator
from .filters import ProductFilter
def get_root_group():
    return  PoductGroup.objects.filter(Q(is_active=True) & Q(group_parent=None))
#-------------------------------------------------------------------------------------------------------------

# Cheapest products
def get_cheapest_products(request,*args, **kwargs):
    products = Product.objects.filter(is_active=True).order_by('price')[:8]
    products_groups =get_root_group()
    context={
        'products':products,
        'products_groups':products_groups,
    }
    return render(request,"product_app/partials/cheapest_products.html",context=context) 
#-------------------------------------------------------------------------------------------------------------

# Latest products
def get_last_products(request,*args, **kwargs):
    products = Product.objects.filter(is_active=True).order_by('-published_date')[:8]
    products_groups = get_root_group()
    context={
        'products':products,
        'products_groups':products_groups,
    }
    return render(request,"product_app/partials/last_products.html",context=context)
#-------------------------------------------------------------------------------------------------------------

def get_popular_product_groups(request,*args, **kwargs):
    product_group=PoductGroup.objects.filter(Q(is_active=True)).annotate(count=Count('products_of_group')).order_by('-count')[:6]
    context={
        'product_group':product_group,
    }
    return render(request,"product_app/partials/popular_product_group.html",context=context)
#-------------------------------------------------------------------------------------------------------------

# Product details
class ProductDetailView(View):
    def get(self,request,slug):
        product=get_object_or_404(Product,slug=slug)
        if product.is_active:
            return render(request,"product_app/product_detail.html",{"product":product})
#-------------------------------------------------------------------------------------------------------------

# Related products
def get_related_products(request,*args, **kwargs):
    current_product=get_object_or_404(Product,slug=kwargs['slug'])
    related_product=[]
    for group in current_product.product_group.all():
        related_product.extend(
            Product.objects.filter(Q(is_active=True) & Q(product_group=group) & ~Q(id=current_product.id))
        )
    return render(request,"product_app/partials/related_products.html",{"related_product":related_product})
#-------------------------------------------------------------------------------------------------------------
# List of all product groups
class ProductGroupsView(View):
    def get(self,request):
        product_groups=PoductGroup.objects.filter(Q(is_active=True)).annotate(count=Count('products_of_group')).order_by('-count')
        return render(request,"product_app/partials/product_groups.html",{"product_groups":product_groups})
    
#-------------------------------------------------------------------------------------------------------------
# List of product groups for filter
def get_product_groups(request):
    product_groups = PoductGroup.objects.annotate(count=Count('products_of_group')).filter(Q(is_active=True) & ~Q(count=0)).order_by('-count')
    return render(request,"product_app/partials/product_groups.html",{"product_groups":product_groups})


#-------------------------------------------------------------------------------------------------------------
# List of brands for filter
def get_brands(request,*args, **kwargs):
    product_group = get_object_or_404(PoductGroup,slug=kwargs['slug'])
    brand_list_id=product_group.products_of_group.filter(is_active=True).values('brand_id')
    brands=Brand.objects.filter(pk__in=brand_list_id).annotate(count=Count('product_of_brands')).filter(~Q(count=0)).order_by('-count')
    return render(request,'product_app/partials/brands.html',{'brands':brands})
#-------------------------------------------------------------------------------------------------------------

# two dropdown in adminpanel
def filter_value_for_feature(request):
    if request.method == "GET":
        feature_id = request.GET.get('feature_id')
        feature_values = FeatureValue.objects.filter(feature_id=feature_id)
        res={fv.value_title:fv.id for fv in feature_values}
        return JsonResponse(data=res,safe=False)
    

#-------------------------------------------------------------------------------------------------------------
def get_features_for_filtre(request,*args, **kwargs):
    product_group = get_object_or_404(PoductGroup,slug=kwargs['slug'])
    features_list=product_group.features_of_group.all()
    features_dict=dict()
    for features in features_list:
        features_dict[features]=features.feature_values.all();
    return render(request,'product_app/partials/features_filter.html',{'feature_dict':features_dict})
    
#-------------------------------------------------------------------------------------------------------------
# List of products for each product group

class ProductsByGroupView(View):
    def get(self,request,*args, **kwargs):
        
        slug = kwargs['slug']
        
        current_group_detection = get_object_or_404(PoductGroup,slug=kwargs['slug'])

        products = Product.objects.filter(Q(product_group=current_group_detection) & Q(is_active=True))
        
        res_aggre = products.aggregate(min=Min('price'),max=Max('price')) # aggregate output is a dictionary
        # price filter
        filters =ProductFilter(request.GET,queryset=products)
        products = filters.qs
        
        # brand filter
        brand_filter = request.GET.getlist('brand')
        if brand_filter:
            products = products.filter(brand__id__in=brand_filter)
            
        features_filter = request.GET.getlist("feature")
        if features_filter:
            products = products.filter(product_features__filter_value__id__in=features_filter).distinct()
            
        # sort type
        sort_type = request.GET.get('sort_type')
        if not sort_type:
            sort_type = "0"
        if sort_type == "1":
            products = products.order_by('price')
        elif sort_type == "2":
            products = products.order_by('-price')
        
# Tip: Always perform all product filters before paging the site and then paging. You can see an example in this code.
        group_slug = slug
        product_per_page = int(request.GET.get('product_numbers',2))
        
        paginator = Paginator(products,product_per_page) 
        page_number = request.GET.get('page') # find number page
        page_obj =paginator.get_page(page_number) # List of products after pagination on the current page
        product_count = products.count() # The total number of products in this group

        # A list of numbers to create a drop-down menu to determine the number of items on each page by the user
        show_count_product = []
        i=product_per_page
        while i< product_count:
            show_count_product.append(i)
            i*=2
        show_count_product.append(i)


        # Always keep the selected value in the list
        if product_per_page not in show_count_product:
            show_count_product.append(product_per_page)

        # Sort the list so that the selected value is in the right place
        show_count_product.sort()


        context = {
            'products' : products,
            'current_group' : current_group_detection,
            'res_aggre' :res_aggre,
            'group_slug' : group_slug,
            'page_obj':page_obj,
            'product_count':product_count,
            'filter':filters,
            'show_count_product':show_count_product,
            'sort_type':sort_type,
            'product_current_number':product_per_page,
        }
        return render(request,'product_app/products.html',context)

#  ______________________________________________________________________________________________________
       
    
# ___________________________________________________________________________________________________________________________________
# Main comparison page: Display products added to comparison list

class ShowCompareListView(View):
    def get(self, request, *args, **kwargs):
        compare_list = CompareProduct(request)
        context = {
            'compare_list' : compare_list,
        }
        return render(request,'product_app/compare_list.html',context)

# -----------------------------------------------
# Display comparison list products table

from .compare import CompareProduct

def compare_table(request):
    compareList = CompareProduct(request)
    
    # Only product ID is not enough and since I need the name and all product information, I got the products
    products = []
    for productId in compareList.compare_product:
        product = Product.objects.get(id=productId)
        products.append(product)
        
    features = []
    for product in products:
        for item in product.product_features.all():
            if item.feature not in features:
                features.append(item.feature)
                
    context = {
        'products' : products,
        'features' : features,
    }
    
    return render(request,'product_app/partials/compare_table.html',context)

# -----------------------------------------------
# Calculate products in comparison list
# Case | Description
# HttpResponse() | Gives raw and simple response to client
# Its content | Can be text, number, HTML, JSON (if with JsonResponse) and...
# In this example | Only returns the number of products in the comparison list (e.g. 3)

templates/partials/products/comment_product.html
{% load render_partial %} 
<div class="reviews-view">
    <div class="reviews-view__list">
        <h3 class="reviews-view__header">Customer Reviews</h3>
        <div class="reviews-list">
            <ol class="reviews-list__content">
                {% for comment in product.comments_product.all %}
                    {% if comment.is_active and comment.comment_parent == None %}
                        <!-- parent comment -->
                        <li class="reviews-list__item">
                            <div class="review">
                                <div class="review__avatar">
                                    <img src="{{ media_url }}images/avatars/avatar-2.jpg" alt="">
                                </div>
                                <div class="review__content">
                                    <div class="review__author">{{ comment.commenting_user.name }}</div>
                                    <div class="review__text">{{ comment.comment_text }}</div>
                                    <div class="review__date">{{ comment.registerdate }}</div>
                                </div>
                            </div>
                            
                            {% if user.is_authenticated %}
                                <div>
                                    <a class="btn btn-info" id="btn_{{ comment.id }}" onclick="showCreateCommentForm({{ product.id }}, {{ comment.id }}, '{{ product.slug }}');">Reply</a>
                                </div>
                                <div id="comment_form_{{ comment.id }}"></div>
                            {% endif %}

                            <!-- replies -->
                            {% for reply in comment.comment_child.all %}
                                {% if reply.is_active %}
                                    <ul class="reviews-list__content" style="list-style: none;">
                                        <li class="reviews-list__item" style="background-color: beige; width: 95%; margin: 10px 5%;">
                                            <div class="review">
                                                <div class="review__avatar">
                                                    <img src="{{ media_url }}images/avatars/avatar-4.jpg" alt="">
                                                </div>
                                                <div class="review__content">
                                                    <div class="review__author">{{ reply.commenting_user.name }}</div>
                                                    <div class="review__text">{{ reply.comment_text }}</div>
                                                    <div class="review__date">{{ reply.registerdate }}</div>
                                                </div>
                                            </div>
                                        </li>
                                    </ul>
                                {% endif %}
                            {% endfor %}
                        </li>
                    {% endif %}
                {% endfor %}
            </ol>
        </div>
    </div>

    {% if user.is_authenticated %}
        <h3 class="reviews-view__header">دیدگاه خود را بنویسید</h3>
        <div class="row">
            <div class="col-12 col-lg-9 col-xl-8">
                {% render_partial "csf:create_comment" slug=product.slug %}
            </div>
        </div>
    {% else %}
        <h5> 
            برای درج دیدگاه خود باید 
            <a href="{% url "account:login" %}?next={% url 'products:product_details' product.slug %}">ورود</a> 
            یا 
            <a href="{% url "account:register" %}?next={% url 'products:product_details' product.slug %}">ثبت نام</a>
            کنید
        </h5>
    {% endif %}
</div>

templates/partials/products/price_filter.html
{% load humanize %}

{% load static %}

<script src="{% static "js/myscript.js" %}"></script>

<div id="accordion">
    <div class="card" style="border: none; color:#868686;">
      <div class="card-header" style="padding:0 0 10px;">
        <a class="card-link" data-toggle="collapse" href="#collapsePrice">
          <button type="button" class="filter__title" data-collapse-trigger style="color:#000;">
            Price<svg class="filter__arrow" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" width="32" height="32" viewBox="0 0 256 256" xml:space="preserve">
              <g style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: none; fill-rule: nonzero; opacity: 1;" transform="translate(1.4065934065934016 1.4065934065934016) ">
                <path d="M 90 24.25 c 0 -0.896 -0.342 -1.792 -1.025 -2.475 c -1.366 -1.367 -3.583 -1.367 -4.949 0 L 45 60.8 L 5.975 21.775 c -1.367 -1.367 -3.583 -1.367 -4.95 0 c -1.366 1.367 -1.366 3.583 0 4.95 l 41.5 41.5 c 1.366 1.367 3.583 1.367 4.949 0 l 41.5 -41.5 C 89.658 26.042 90 25.146 90 24.25 z" style="stroke: none; stroke-width: 1; stroke-dasharray: none; stroke-linecap: butt; stroke-linejoin: miter; stroke-miterlimit: 10; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;" transform=" matrix(1 0 0 1 0 0) " stroke-linecap="round" />
              </g>
            </svg>
          </button>
        </a>
      </div>
      <div id="collapsePrice" class="collapse" data-parent="#accordion">
        <div class="card-body" style="padding: 0;">
            <span><strong id="sel_price">{{res_aggre.max|intcomma}}</strong> تومان</span>
                {% comment %} {{filter.form}} {% endcomment %}
                <br>
                <input type="range" name="price" min="{{res_aggre.min}}" max="{{res_aggre.max}}" value="{{res_aggre.max}}" oninput="showVal(this.value)" onchange="showVal(this.value)">
                <br>
                <span style="color: black;">{{res_aggre.min|intcomma}}
                &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
                {{res_aggre.max|intcomma}}</span>
        </div>
      </div>
    </div>
  </div>

templates/partials/products/product_box.html
{% load humanize %}

{% if type == 1 %}
    
                    <div class="product-card" style="width: 200px !important; margin-left: 12px;" >
                    <div class="product-card__image">
                    <a href="{{product.get_absolute_url}}">
                    <img src="{{media_url}}{{product.image_name}}" alt="" />
                    </a>
                </div>
                    <div class="product-card__info">
                    <div class="product-card__name">
                    <a href="{{product.get_absolute_url}}">{{ product.produce_name }}</a>
                    </div>
                </div>
                <div class="product-card__actions">
                    
                         {% if product.get_number_in_warehouse <= 0 %}
                            <span style="color:red;">Out of Stock</span>
                        {% else %}
                            {% if product.price > product.get_price_by_discount %}
                                <div class="product-card__prices"><del>{{ product.price|floatformat:0|intcomma }} تومان </del></div>
                                <div class="product-card__prices" style="color:red;" >{{ product.get_price_by_discount|floatformat:0|intcomma }} تومان </div>
                            {% else %}
                                <div class="product-card__prices">{{ product.price|floatformat:0|intcomma }} تومان </div>
                            {% endif %}
                        {% endif %}

                        <div class="product-card__buttons">
                        {% if product.get_number_in_warehouse > 0 %}
                            <button class="btn btn-primary product-card__addtocart" type="button" onclick="add_to_shop_cart({{product.id}},1)">
                            Add to Cart</button>
                        {% endif %}
                        {% if user.is_authenticated %}
                            <button 
                            class="btn btn-light btn-svg-icon product-card__wishlist" 
                            id="favorite-btn-{{ product.id }}"
                            onclick="addTofavorites({{ product.id }})"
                            >
                            <i class="fa {% if product.get_user_favorite %}fa-heart{% else %}fa-heart-broken{% endif %}"></i>
                            <span class="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                            </button>
                    {% endif %}

                        </div>
                    </div>
                </div>
{% elif type == 2 %}
                    <div class="product-card" style="width: 200px !important; margin-left: 12px;" >
                    <div class="product-card__image">
                    <a href="{{product.get_absolute_url}}">
                    <img src="{{media_url}}{{product.image_name}}" alt="" />
                    </a>
                </div>
                <div class="new_badge">
                    جدید
                </div>
                    <div class="product-card__info">
                    <div class="product-card__name">
                    <a href="{{product.get_absolute_url}}">{{ product.produce_name }} تومان </a>
                    </div>
                </div>
                
                <div class="product-card__actions">
                        {% if product.get_number_in_warehouse <= 0 %}
                            <span style="color:red;">Out of Stock</span>
                        {% else %}
                            {% if product.price > product.get_price_by_discount %}
                                <div class="product-card__prices"><del>{{ product.price|floatformat:0|intcomma }} تومان </del></div>
                                <div class="product-card__prices" style="color:red;" >{{ product.get_price_by_discount|floatformat:0|intcomma }} تومان </div>
                            {% else %}
                                <div class="product-card__prices">{{ product.price|floatformat:0|intcomma }} تومان </div>
                            {% endif %}
                        {% endif %}

                        <div class="product-card__buttons">
                            {% if product.get_number_in_warehouse > 0 %}
                                <button class="btn btn-primary product-card__addtocart" type="button" onclick="add_to_shop_cart({{product.id}},1)">
                                Add to Cart</button>
                            {% endif %}
                            {% if user.is_authenticated %}
                                <button 
                                class="btn btn-light btn-svg-icon product-card__wishlist" 
                                id="favorite-btn-{{ product.id }}"
                                onclick="addTofavorites({{ product.id }})"
                                >
                                <i class="fa {% if product.get_user_favorite %}fa-heart{% else %}fa-heart-broken{% endif %}"></i>
                                <span class="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                                </button>
                        {% endif %}
                        <button class="btn btn-light btn-svg-icon btn-svg-icon--fake-svg product-card__wishlist" type="button">
                        <i class="fa fa-shopping-cart"></i>
                        <span class="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                        </button>
            
                        </div>
                    </div>
                </div>
{% elif type == 3 %}
                                            <div class="products-list__item">
                                                <div class="product-card">
                                                    <div class="product-card__badges-list">
                                                        <div class="product-card__badge product-card__badge--new">جدید</div>
                                                    </div>
                                                    <div class="product-card__image">
                                                        <a href="{% url 'products:product_details' slug=product.slug %}">
                                                            <img src="{{media_url}}{{product.image_name}}" alt="">
                                                        </a>
                                                    </div>
                                                    <div class="product-card__info">
                                                        <div class="product-card__name"><a href="{% url 'products:product_details' slug=current_group.slug %}">{{ product.produce_name }}</a></div>

                                                    </div>
                                                    <div class="product-card__actions">
                                                        <div class="product-card__availability">
                                                            
                                                            {% if product.get_number_in_warehouse <= 0 %}
                                                                <span style="color:red;">Out of Stock</span>
                                                            {% else %}
                                                                {% if product.price > product.get_price_by_discount %}
                                                                    <div class="product-card__prices"><del>{{ product.price|floatformat:0|intcomma }} تومان </del></div>
                                                                    <div class="product-card__prices" style="color:red;" >{{ product.get_price_by_discount|floatformat:0|intcomma }} تومان </div>
                                                                {% else %}
                                                                    <div class="product-card__prices">{{ product.price|floatformat:0|intcomma }} تومان </div>
                                                            {% endif %}
                                                        {% endif %}
                                                        </div>
                                                        <div class="product-card__buttons">
                                                            {% if product.get_number_in_warehouse > 0 %}
                                                                <button class="btn btn-primary product-card__addtocart" type="button" onclick="add_to_shop_cart({{product.id}},1)">
                                                                    Add to Cart</button>
                                                            {% else %}
                                                            <span style="color:red;">Out of Stock</span>
                                                            {% endif %}

                                                            {% if user.is_authenticated %}
                                                            <button 
                                                            class="btn btn-light btn-svg-icon product-card__wishlist" 
                                                            id="favorite-btn-{{ product.id }}"
                                                            onclick="addTofavorites({{ product.id }})"
                                                            >
                                                            <i class="fa {% if product.get_user_favorite %}fa-heart{% else %}fa-heart-broken{% endif %}"></i>
                                                            <span class="fake-svg-icon fake-svg-icon--wishlist-16"></span>
                                                            </button>
                                                            {% endif %}
                                                        </div>
                                                    </div>
                                                </div>
                                            </div>
{% endif %}

templates/partials/products/root_group.html
      <div class="block-header">
        <h3 class="block-header__title">{{ title }}</h3>
        <div class="block-header__divider"></div>
        <ul class="block-header__groups-list">
          <li>
            <button
              type="button"
              class="block-header__group block-header__group--active">همه</button>
          </li>
          {% for group in products_groups %}
            <li>
                <button type="button" class="block-header__group">{{group.group_title}}</button>
            </li>
        {% endfor %}
        </ul>
        <div class="block-header__arrows-list">
          <button
            class="block-header__arrow block-header__arrow--left"
            type="button"
          >
            <i class="fas fa-angle-right"></i>
          </button>
          <button
            class="block-header__arrow block-header__arrow--right"
            type="button"
          >
            <i class="fas fa-angle-left"></i>
          </button>
        </div>
      </div>