apps/main/urls.py
from django.urls import path
from .views import index,contactus,SliderView
app_name="main"
urlpatterns = [
    path("",index,name="index"),
    path("contactus",contactus,name="contactus"),
    # path("test/",test_view,name='test_view')
    path('sliders/',SliderView.as_view(),name="sliders"),
    # path('error/',handler404)
]

apps/orders/urls.py
from django.urls import path
from . import views

app_name = "orders"
urlpatterns = [
    
    path('shop_cart/', views.ShopCartView.as_view(), name='shop_cart'),
    path("show_shop_cart/",views.show_shop_cart_View,name="show_shop_cart"),
    path("add_to_shop_cart/", views.add_to_shop_cart_view, name="add_to_shop_cart"),
    path("delete_from_shop_cart/",views.delete_from_shop_cart_View,name="delete_from_shop_cart"),
    path("update_shop_cart/",views.update_shop_cart,name="update_shop_cart"),
    path("status_of_shop_cart/",views.status_of_shop_cart,name="status_of_shop_cart"),
    path("create_order/",views.CreateOrderView.as_view(),name="create_order"),
    path("checkout_order/<int:order_id>/",views.CheckoutOrderViwe.as_view(),name="checkout_order"),
    path("applay_coupon/<int:order_id>/",views.ApplayCoupon.as_view(),name="applay_coupon"),
]

shop/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("",include("apps.main.urls",namespace="main")),
    path("accounts/",include("apps.accounts.urls",namespace="accounts")),
    path("products/",include("apps.products.urls",namespace="products")),
    path("orders/",include("apps.orders.urls",namespace="orders")),
    path("discounts/",include("apps.discounts.urls",namespace="discounts")),
    path("payments/",include("apps.payments.urls",namespace="payments")),
    path("warehouses/",include("apps.warehouses.urls",namespace="warehouses")),
    path("csf/",include("apps.comment_scoring_favorites.urls",namespace="csf")),
    path("search/",include("apps.search.urls",namespace="search")),
    path("test_api/",include("apps.test_api.urls",namespace="test_api")),
    
    
    path("ckeditor",include('ckeditor_uploader.urls')),
] + static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)


handler404 = "apps.main.views.handler404"

templates/orders_app/checkout.html
{% extends "main_template.html" %}
{% load render_partial %} 
{% block title %}Order Invoice{% endblock title %} 
{% load humanize %}
{% block content %} 

		<!-- site__body -->
		<div class="site__body">
			<div class="page-header">
				<div class="page-header__container container">
					<div class="page-header__breadcrumb">
						<nav aria-label="breadcrumb">
							<ol class="breadcrumb">
										<li class="breadcrumb-item"><a href="{% url 'main:index' %}">Home</a>
									/
								</li>
								
										<li class="breadcrumb-item active" aria-current="page">Payment</li>
							</ol>
						</nav>
					</div>
					<div class="page-header__title">
									<h1>Payment</h1></div>
				</div>
			</div>
			<div class="checkout block">
				<div class="container">
					<div class="row">
						<div class="col-12 col-lg-6 col-xl-7">
							<div class="card mb-lg-0">
								<div class="card-body">
									<form action="{% url "orders:checkout_order" order_id=order.id %}" method="post">
										{% csrf_token %}
											<h3 class="card-title">Payment Details</h3>
										<div class="form-row">
											<div class="form-group col-md-6">
													<label for="checkout-first-name">Name</label>
												{{form_order.name}}
											</div>
											<div class="form-group col-md-6">
													<label for="checkout-last-name">Family Name</label>
												{{form_order.family}}
											</div>
											<div class="form-row">
												<div class="form-group col-md-6">
														<label for="checkout-email">Email Address</label>
													{{form_order.email}}
												</div>
												<div class="form-group col-md-6">
														<label for="checkout-phone">Phone</label>
													{{form_order.phone_number}}
												</div>
											</div>
										</div>
										<div class="form-group">
														<label for="checkout-street-address">Address </label>
												{{form_order.address}}
										</div>
										
									</div>
									<div class="card-divider"></div>
									<div class="card-body">

										<div class="form-group">
														<label for="checkout-comment">Order Description <span class="text-muted">(Optional)</span></label>
											{{form_order.description}}
										</div>
									</div>
								</div>
							</div>
					
							<div class="col-12 col-lg-6 col-xl-5 mt-4 mt-lg-0">
								<div class="card mb-0">
									<div class="card-body">
													<h3 class="card-title">Your Order</h3>
										<table class="checkout__totals">
											<thead class="checkout__totals-header">
												<tr>
																<th>Product Name</th>
																<th>Quantity</th>
													<th>Total</th>
												</tr>
											</thead>
											<tbody class="checkout__totals-products">
												{% for item in shop_cart %}
													<td> 
														{{item.product.produce_name}}
													</td>
													<td>
														{{item.quantity}}
													</td>
													<td>
														{{item.total_price|intcomma}}
													</td>

												</tr>
												{% endfor %}
												<tr>
											</tbody>
											<tbody class="checkout__totals-subtotals">
												<tr>
													<th colspan="2">جمع جزء</th>
													<td>{{total_price|intcomma}} تومان</td>
												</tr>
												<tr>
													<th colspan="2">حمل و نقل</th>
													{% if delivery == 0 %}
														<td>رایگان</td>
													{% else %}
													<td>{{delivery|intcomma}} تومان</td>
													{% endif %}
												</tr>
												<tr>
													<th colspan="2">مالیات</th>
													<td>{{tax|intcomma}} تومان</td>
												</tr>
											</tbody>
											<tfoot class="checkout__totals-footer">
												<tr style="color:green; font-weight: bold;">
													<th colspan="2">Total</th>
													<td>{{order_final_price|intcomma}} تومان</td>

												</tr>
											</tfoot>
										</table>

											<br>
											<h3 class="card-title">جزئیات حمل و نقل</h3>
											<div class="form-group">
			
												{{form_order.payment}}
											</div>
											<br>
										<div class="checkout__agree form-group">
											<div class="form-check"><span class="form-check-input input-check"><span class="input-check__body"><input class="input-check__input" type="checkbox" id="checkout-terms"> <span class="input-check__box"></span>
												<svg class="input-check__icon" width="9px" height="7px">
													<use xlink:href="images/sprite.svg#check-9x7"></use>
												</svg>
												</span>
												</span>
												<label class="form-check-label" for="checkout-terms">من <a target="_blank" href="terms-and-conditions.html">قوانین و مقررات</a> را خوانده و موافقم *</label>
	
											</div>
										</div>

										<form action="{% url 'orders:checkout_order' order_id=order.id %}" style="display: flex; justify-content: center; gap: 10px; align-items: center;" method="post">
										{% csrf_token %}
										{{form_coupon}}
										<button 
											type="submit" 
											class="btn btn-primary btn-block" 
											style="
												padding: 12px 24px;
												font-size: 1.1rem;
												min-width: 120px;
											">
											اعمال کد
										</button>
										
										<br>
									<button type="submit" class="btn btn-primary btn-xl btn-block">ثبت سفارش</button>
								</form>
								</div>
							</div>
						</div>
					</div>
				</div>
			</div>
		</div>
			<!-- site__body / end -->

{% endblock content %}

templates/orders_app/shop_cart.html
{% extends "main_template.html" %}
{% load render_partial %} 
{% block title %}Shopping Cart{% endblock title %} 

{% block content %} 

<div id="shop_cart_list">
    {% render_partial 'orders:show_shop_cart' %}
</div>


{% endblock content %}